name = "ai-image-generator"
main = "src/index.ts"
compatibility_date = "2024-10-22"
compatibility_flags = ["nodejs_compat"]

[vars]
HUGGING_FACE_API_KEY = "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"

[observability]
enabled = true
